# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessao',
            options={'verbose_name_plural': 'Sessões'},
        ),
        migrations.AlterField(
            model_name='sessao',
            name='dataTime',
            field=models.DateField(),
        ),
    ]
