# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20170531_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='time',
            field=models.TimeField(verbose_name='%H:%i'),
        ),
    ]
