# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20170531_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='sessao',
        ),
        migrations.AddField(
            model_name='sessao',
            name='filme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema.Filme'),
            preserve_default=False,
        ),
    ]
