# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_auto_20170603_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessao',
            name='filme',
        ),
        migrations.AddField(
            model_name='sessao',
            name='filme',
            field=models.ManyToManyField(to='cinema.Filme'),
        ),
    ]
